// <auto-generated />
namespace CompanyDbWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usingFluentAPIforTBAs2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usingFluentAPIforTBAs2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708041907144_usingFluentAPIforTBAs2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
